### ISSUE TITLE
Error loading after recent Fedora update

### ISSUE THREAD

**Issue by joeldeteves** [flathub/com.bitwarden.desktop#131]
I updated this flatpak on Fedora 37 recently and it stopped working. Here's the trace:

```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=bitwarden --file-forwarding com.bitwarden.desktop @@u %U @@
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token  in JSON at position 605642
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/app/Bitwarden/resources/app.asar/main.js:6643:43)
    at get store [as store] (/app/Bitwarden/resources/app.asar/main.js:6854:43)
    at new Conf (/app/Bitwarden/resources/app.asar/main.js:6707:32)
    at new ElectronStore (/app/Bitwarden/resources/app.asar/main.js:10432:3)
    at new ElectronStorageService (/app/Bitwarden/resources/app.asar/main.js:49542:22)
    at new Main (/app/Bitwarden/resources/app.asar/main.js:52372:31)
    at 99726 (/app/Bitwarden/resources/app.asar/main.js:43754:18)
    at __webpack_require__ (/app/Bitwarden/resources/app.asar/main.js:54772:42)
    at /app/Bitwarden/resources/app.asar/main.js:54828:37
Gtk-Message: 00:00:45.193: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:00:45.193: Failed to load module "pk-gtk-module"
Gtk-Message: 00:00:45.194: Failed to load module "canberra-gtk-module"
Gtk-Message: 00:00:45.194: Failed to load module "pk-gtk-module"
[2:0111/000045.205755:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0111/000045.205823:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0111/000045.215310:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[2:0111/000045.215377:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property

```

**Comment by ghisvail** [comment]
Worked for me on Fedora 37, and now NixOS and Debian.

Have you tried with the most recent version?

**Comment by ghisvail** [comment]
Closing as won't fix. No actionable way forward.
