### ISSUE TITLE
Error showing menu bar

### ISSUE THREAD

**Issue by zastrixarundell** [flathub/com.bitwarden.desktop#134]
The flatpak version of bitwarden has a missing menu bar. As shown under this screenshot:

![image](https://user-images.githubusercontent.com/30195425/212670574-3da43c14-24e1-4574-9153-f82801604cb4.png)

Top-left is the official AppImage while bottom right is the flatpak version. 

```
$ flatpak run com.bitwarden.desktop 

(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
[2:0116/124431.435630:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0116/124431.435678:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0116/124431.490257:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0116/124431.490324:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0116/124431.490354:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:51261:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:50762:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:50688:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:50679:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:50658:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:50654:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:50679:79)
    at IpcMainImpl.emit (node:events:527:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/app/Bitwarden/resources/app.asar/main.js:51261:23)
    at MessagingMain.updateTrayMenu (/app/Bitwarden/resources/app.asar/main.js:50762:28)
    at MessagingMain.onMessage (/app/Bitwarden/resources/app.asar/main.js:50688:22)
    at MessagingMain.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:50679:151)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:50658:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/app/Bitwarden/resources/app.asar/main.js:50654:12)
    at IpcMainImpl.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:50679:79)
    at IpcMainImpl.emit (node:events:527:28)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

While using KDE I have a workaround with an extension to show that menu at the bottom of my screen but I'd rather have it in the app while wanting to manually sync my vault.

**Comment by zastrixarundell** [comment]
To clear space I wiped my home directory and after recreating the user the issues seems to have fixed itself. Marking this as closed.
