### ISSUE TITLE
Bitwarden Flatpak crashes on launch

### ISSUE THREAD

**Issue by berz** [flathub/com.bitwarden.desktop#166]
Bitwarden crashes repeatably on launch when installed through flatpak on an up to date version of Pop!_OS 22.04 LTS. 

No window or error message is shown after starting the application. When launching from a terminal the output contains the error message `SyntaxError: Unterminated string in JSON at position 233472`. This seems to be a packaging issue as the appimage on bitwarden.com works fine (same version, 2023.9.3).
```
qvdb@marvin ~ $ flatpak run com.bitwarden.desktop
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unterminated string in JSON at position 233472
    at JSON.parse (<anonymous>)
    at Conf._deserialize (/app/Bitwarden/resources/app.asar/main.js:7833:43)
    at get store [as store] (/app/Bitwarden/resources/app.asar/main.js:8044:43)
    at new Conf (/app/Bitwarden/resources/app.asar/main.js:7897:32)
    at new ElectronStore (/app/Bitwarden/resources/app.asar/main.js:11630:3)
    at new ElectronStorageService (/app/Bitwarden/resources/app.asar/main.js:53317:22)
    at new Main (/app/Bitwarden/resources/app.asar/main.js:53764:31)
    at 64164 (/app/Bitwarden/resources/app.asar/main.js:44265:18)
    at __webpack_require__ (/app/Bitwarden/resources/app.asar/main.js:58132:42)
    at /app/Bitwarden/resources/app.asar/main.js:58188:37
Gtk-Message: 19:00:49.167: Failed to load module "xapp-gtk3-module"
Gtk-Message: 19:00:49.322: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:00:49.325: Failed to load module "canberra-gtk-module"
```

**Comment by ghisvail** [comment]
Could you try with the latest build?

**Comment by berz** [comment]
I tried the latest version on flathub (`flatpak install com.bitwarden.desktop/x86_64/stable`) and am still getting the same error (`Unterminated string in JSON`).

**Comment by ghisvail** [comment]
The only I can think of would be some residual faulty data in cache.

`flatpak uininstall com.bitwarden.desktop --delete-data`

Otherwise, this needs to be escalated upstream. I am unable to reproduce and no other Ubuntu LTS user confirmed your problem.

**Comment by berz** [comment]
Clearing the data resolved the issue. Thanks for your support!
