### ISSUE TITLE
Bitwarden crashes on laucher after showing a grey screen with the task bar

### ISSUE THREAD

**Issue by RiQuY** [flathub/com.bitwarden.desktop#170]
Bitwarden crashes on laucher after showing a grey screen with the task bar.

System info
--
OS: openSUSE Tumbleweed x86_64
Kernel: 6.6.1-1-default
Shell: bash 5.2.15
Resolution: 2560x1440
DE: Hyprland
WM: sway
Terminal: kitty
CPU: AMD Ryzen 7 1700X (16) @ 3.400GHz
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT
Memory: 6535MiB / 32016MiB

Bitwarden version (Flatpak): 2023.10.1

Log output
--
Running Bitwarden from console gives me this output:
```
ricardo@localhost:~> flatpak run com.bitwarden.desktop 

(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:2) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:47305:55)
    at Generator.next (<anonymous>)
    at /app/Bitwarden/resources/app.asar/main.js:47271:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/app/Bitwarden/resources/app.asar/main.js:47267:12)
    at BiometricsService.init (/app/Bitwarden/resources/app.asar/main.js:47304:16)
    at Main.<anonymous> (/app/Bitwarden/resources/app.asar/main.js:54050:46)
    at Generator.next (<anonymous>)
    at fulfilled (/app/Bitwarden/resources/app.asar/main.js:53942:58)
(node:2) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by RiQuY** [comment]
This error appears on the version obtained through the openSUSE package manager (zypper) but the app don't crashes there.

**Comment by sagehane** [comment]
I get identical errors on NixOS with River (wayland compositor), although I don't see the `Check failed: false.` stuff at the end. The screen briefly pops up and crashes immediately.

**Comment by quexten** [comment]
In case this is an issue, please report it upstream to https://github.com/bitwarden/clients, as per https://github.com/flathub/com.bitwarden.desktop/issues/324.
