### ISSUE TITLE
Doesn't launch on ARM

### ISSUE THREAD

**Issue by nedrichards** [flathub/com.bitwarden.desktop#4]
When launching this on my ARM machine I get an error in keytar:

```
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]: App threw an error during load
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]: Error: Cannot find module '../build/Release/keytar.node'
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module._resolveFilename (module.js:543:15)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Function.Module._resolveFilename (/app/main/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Function.Module._load (module.js:473:25)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module.require (module.js:586:17)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at require (internal/module.js:11:18)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Object.<anonymous> (/app/main/node_modules/keytar/lib/keytar.js:1:169)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Object.<anonymous> (/app/main/node_modules/keytar/lib/keytar.js:61:3)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module._compile (module.js:642:30)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Object.Module._extensions..js (module.js:653:10)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module.load (module.js:561:32)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]: A JavaScript error occurred in the main process
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]: Uncaught Exception:
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]: Error: Cannot find module '../build/Release/keytar.node'
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module._resolveFilename (module.js:543:15)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Function.Module._resolveFilename (/app/main/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Function.Module._load (module.js:473:25)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module.require (module.js:586:17)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at require (internal/module.js:11:18)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Object.<anonymous> (/app/main/node_modules/keytar/lib/keytar.js:1:169)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Object.<anonymous> (/app/main/node_modules/keytar/lib/keytar.js:61:3)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module._compile (module.js:642:30)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Object.Module._extensions..js (module.js:653:10)
Oct 04 13:52:59 endless-arm com.bitwarden.desktop.desktop[2096]:     at Module.load (module.js:561:32)
```
As I remember, this needs some sort of binary component, maybe that's missing?

**Comment by ghisvail** [comment]
Closing this issue since the build is now restricted to `x86_64` only.
